[build]
  command = "npx pnpm i --store=node_modules/.pnpm-store --frozen-lockfile && npm run docs:build"
  publish = "docs/.vitepress/dist"

  [build.environment]
    NODE_VERSION = "16"
    NPM_FLAGS = "--version"
