name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build all
        run: pnpm build -a

      - name: Build assets
        run: pnpm build:assets

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test:cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./test/.coverage/clover.xml
          flags: unittests
          verbose: true
