name: Release Github

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Build Release Assets
        run: pnpm build:asset

      - name: Create releaselog
        run: pnpm releaselog

      - name: Check prerelease
        id: prerelease
        uses: actions/github-script@v6
        with:
          script: return /-/.test("${{ github.ref }}")

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          prerelease: ${{ steps.prerelease.outputs.result }}
          body_path: 'RELEASELOG.md'
          files: 'dist/**.zip'
